Repository SBSystem/SmallBlogSystem, pull requests merged in 2018-03, with the labels that each got.

#17 Zaktualizowano CHANGELOG
  CHANGELOG.md
Labels: Status: Zmergowano

#20 Dodano licencję
  LICENSE
Labels: Krytyczne, Status: Zmergowano, Ważne

#15 [Kernel] Zdeprecjonowano metody configu i loggera
  src/SmallBlogSystem/Kernel.php
Labels: Status: Zmergowano, Zdeprecjonowane

#13 [BugFix] Poprawiono błędy w pliku Contributing.md
  CONTRIBUTING.md
Labels: Status: Czeka na review, Status: Zmergowano

#25 [BugFix] Dodano notkę o wykorzystaniu ikonki z icons8
  README.md
  sbs-logo.png
Labels: Basic, Status: Czeka na review, Ważne

#27 [Kernel] Dodano ORM
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  config/packages/prod/doctrine.yaml
  config/routes/annotations.yaml
  phpunit.xml
  src/Entity/.gitignore
  src/Migrations/.gitignore
  src/Repository/.gitignore
  symfony.lock
Labels: Basic, Kernel, Status: Czeka na review

#29 [Kernel] [Basic] Dodano doctrine maker
  composer.json
  composer.lock
  config/bundles.php
  src/Entity/Settings.php
  src/Entity/Users.php
  src/Migrations/Version20180311093545.php
  src/Migrations/Version20180311093857.php
  src/Repository/SettingsRepository.php
  src/Repository/UsersRepository.php
  symfony.lock
Labels: :satellite: Status: Czeka na review, Basic, Kernel

#33 [Basic] Zaktualizowano CHANGELOG.
  CHANGELOG.md
Labels: :satellite: Status: Czeka na review, Basic

#35 [Basic] Dodano testy dla Kernela
  config/routes.yaml
  src/Controller/AdminController.php
  src/Controller/IndexController.php
  src/Entity/Categories.php
  src/Entity/Comment.php
  src/Entity/Posts.php
  src/Entity/Settings.php
  src/Entity/Users.php
  src/SmallBlogSystem/Kernel.php
  src/SmallBlogSystem/TemplatesReturn/BasicTemplatesReturn.php
  src/SmallBlogSystem/TemplatesReturn/IndexTemplatesReturn.php
  src/SmallBlogSystem/TemplatesReturn/TwigTemplatesConfig.php
  src/SmallBlogSystem/Users/User.php
  templates/adminDashboard.html.twig
  tests/KernelTest.php
Labels: :satellite: Status: Czeka na review, Basic, Kernel

#38 [Basic] Added symfony/asset
  composer.json
  composer.lock
Labels: :satellite: Status: Czeka na review, Basic

#41 Add webpack configuration
  assets/js/admin.js
  assets/js/front.js
  assets/scss/admin/admin.scss
  assets/scss/front/front.scss
  assets/scss/shared/shared.scss
  package.json
  postcss.config.js
  webpack.config.js
  yarn.lock
Labels: :heavy_check_mark: Status: Zaakceptowane, :x: Status: Odrzucone, Basic

#42 [Basic] Zaktualizowano CONTRIBUTING.md
  CONTRIBUTING.md
Labels: :satellite: Status: Czeka na review, Basic
