Repository SBSystem/SmallBlogSystem, pull requests merged in 2018-02, with the labels that each got.

#1 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Critical, Feature

#3 Aktualizacja README.md
  README.md
Labels: Krytyczne, Review, Tłumaczenie

#4 Przetłumaczono z j. angielskiego na j.polski
  CONTRIBUTING.md
Labels: Krytyczne, Review, Tłumaczenie, Ważne

#9 Dodano kernel
  .gitignore
  src/SmallBlogSystem/Kernel.php
  src/SmallBlogSystem/Level/KernelStartInfo.php
  src/SmallBlogSystem/Level/LogLevel.php
  src/SmallBlogSystem/Managers/BasicManager.php
  src/SmallBlogSystem/Managers/ConfigManager.php
  src/SmallBlogSystem/Managers/LogManager.php
  src/SmallBlogSystem/Managers/config.php
Labels: Krytyczne, Review, Ważne

#11 Stworzono bazowy template Twiga.
  src/Controller/index.php
  src/SmallBlogSystem/Managers/config.php
  src/SmallBlogSystem/TemplatesReturn/IndexTemplatesReturn.php
  templates/base.html.twig
  templates/index.html.twig
Labels: Feature, Krytyczne, Status: Zaakceptowane

#16 Stworzono CHANGELOG
  CHANGELOG.md
Labels: Status: Zmergowano
